# Generated by Django 4.2.7 on 2024-02-23 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.rarity'),
        ),
        migrations.AlterField(
            model_name='lightcone',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_cones', to='core.rarity'),
        ),
    ]
