# Generated by Django 4.2.7 on 2023-11-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Paths',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
