# Generated by Django 4.2.7 on 2024-02-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_character_rarity_alter_lightcone_rarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rarity',
            old_name='star',
            new_name='name',
        ),
    ]
