# Generated by Django 4.2.7 on 2023-11-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_path_alter_element_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('rarity', models.IntegerField(max_length=1)),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.element')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.path')),
            ],
        ),
    ]
