# Generated by Django 4.2.7 on 2023-11-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='rarity',
            field=models.IntegerField(),
        ),
    ]
