# Generated by Django 4.2.7 on 2023-11-10 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_character_rarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='path',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='LightCone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rarity', models.IntegerField()),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_cones', to='core.element')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='light_cones', to='core.path')),
            ],
        ),
    ]
