# Generated by Django 4.2.7 on 2024-02-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_rarity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rarity',
            old_name='name',
            new_name='star',
        ),
    ]
