# Generated by Django 4.2.7 on 2024-01-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_element_options_alter_path_options_lightcone'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/elements/'),
        ),
        migrations.AddField(
            model_name='path',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/paths/'),
        ),
    ]
